### ISSUE TITLE
FR-022 alias

### ISSUE THREAD

**Issue by lorddusk** [CrawlerEmporium/5eCrawler#5]
**Feature Request**: alias

**Who would use it?** nitpicky people
**How would it work?** ``!alias <new_command> <reserved_command>``

**Why should this be added?** Personally, i think its pointless, but... people like to have `!rc`  versus `!randcharactercreationtool`  (yes, I know that's not a real thing)

- LordDusk#0001
Votes: +0 / -0

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Resolved - fixed like ages ago
