### ISSUE TITLE
FR-035 Ignore

### ISSUE THREAD

**Issue by lorddusk** [CrawlerEmporium/5eCrawler#6]
**Feature Request:** Ignore

**Who would use it?** moderator
**How would it work?** [`!ignorethis`]
**Why should this be added?** moderator tool to make the bot ignore a channel - for admins (this is just a duplicate for specifically locking the bot rights out in a channel)

- Modnar#2707
Votes: +0 / -0

**Comment by 5ecrawlreporter** [comment]
Note - LordDusk#0001

Resolved - Won't implement. You as a server owner have to do this with permissions yourself.
