### ISSUE TITLE
BUG-65 The command `!class barbarian 7` returns a 5th-level Unearthed Arcana class feature. The class feature has the same name as a 7th-level feature presented in Tasha's Cauldron of Everything, which is likely the source of the confusion

### ISSUE THREAD

**Issue by crawltracker** [CrawlerEmporium/5eCrawler#89]
**What is the bug?**: The command `!class barbarian 7` returns a 5th-level Unearthed Arcana class feature. The class feature has the same name as a 7th-level feature presented in Tasha's Cauldron of Everything, which is likely the source of the confusion.
**Severity**: Low
**Steps to reproduce**: Use the command `!class barbarian 7` to see the relevant result, including both an accurate 7th-level feature from the PHB and a misplaced 5th-level feature from Unearthed Arcana.  
**Context**: Noticed when using `!class barbarian 7` to learn the class abilities gained by a Barbarian upon reaching level 7. The bug doesn't seem to occur via any other commands.

- FlatSoda#6200
Verification: 0

**Comment by lorddusk** [comment]
No longer relevant, as you can no longer request specific levels for classes.
